[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-global-shortcut = "2.3.1"
core-graphics = { version = "0.25.0", features = ["default"] }
core-graphics-types = "0.2.0"
core-foundation = "0.10.1"
objc2-app-kit = { version = "0.3.2", features = ["NSEvent", "block2"] }
objc2-foundation = { version = "0.3.2", features = ["NSObject"] }
block2 = "0.6.2"
